
import React from 'react';
import { ArrowLeft, ShieldAlert, Scale, BrainCircuit, Cpu, Zap, Globe, Lock, Info } from 'lucide-react';
import { useNavigate } from 'react-router-dom';

const TermsScreen: React.FC = () => {
  const navigate = useNavigate();

  const sections = [
    {
      icon: <BrainCircuit className="text-blue-500" size={20} />,
      title: "Neural Advisory Disclosure",
      content: "Alex Core v3 is an Advanced Large Language Model integrated with real-time market snapshots. All outputs, signals, and analyses generated by the AI are for informational and educational purposes only. They do not constitute financial advice, investment recommendations, or a guarantee of performance. Users must exercise independent judgment before executing any trades."
    },
    {
      icon: <ShieldAlert className="text-rose-500" size={20} />,
      title: "Market & Capital Risk",
      content: "Foreign Exchange (Forex), Cryptocurrencies, and Commodity trading carry a high level of risk and may not be suitable for all investors. The high degree of leverage can work against you as well as for you. You should not invest money that you cannot afford to lose. Past performance of any trading system or methodology is not necessarily indicative of future results."
    },
    {
      icon: <Zap className="text-amber-500" size={20} />,
      title: "Execution & Connectivity",
      content: "LumaTrade FX routes orders via the MetaTrader 5 (MT5) Bridge. You acknowledge that electronic trading platforms are subject to technical failures, latency, and slippage. We are not responsible for losses incurred due to platform downtime, delayed market data feeds, or incorrect trade execution resulting from terminal synchronization issues."
    },
    {
      icon: <Lock className="text-emerald-500" size={20} />,
      title: "Institutional Compliance",
      content: "By linking an MT5 account and enabling 'Real Mode', you confirm that you are compliant with your local regulatory jurisdiction. LumaTrade is a quantitative interface and does not act as a broker or custodian of funds. All financial transactions occur within the infrastructure of your connected MT5 server."
    },
    {
      icon: <Globe className="text-blue-400" size={20} />,
      title: "Data Fidelity Protocols",
      content: "The grounded intelligence used by Alex Core v3 relies on external market data providers. While we strive for 100% data integrity, we do not warrant the accuracy or completeness of the market data snapshots provided. Discrepancies between the LumaTrade interface and your MT5 terminal may occur during periods of extreme volatility."
    }
  ];

  return (
    <div className="min-h-screen bg-slate-950 flex flex-col relative overflow-x-hidden">
      {/* Background decor */}
      <div className="absolute inset-0 opacity-[0.03] pointer-events-none" style={{ backgroundImage: 'radial-gradient(#3b82f6 1px, transparent 0)', backgroundSize: '40px 40px' }}></div>
      
      {/* Header */}
      <div className="px-5 py-6 flex items-center gap-4 border-b border-slate-800/50 glass-dark sticky top-0 z-50">
        <button 
          onClick={() => navigate(-1)}
          className="w-10 h-10 flex items-center justify-center bg-slate-900 border border-slate-800 rounded-xl text-slate-400 active:scale-95 transition-all shadow-lg"
        >
          <ArrowLeft size={20} />
        </button>
        <div>
          <h2 className="text-xl font-black text-white uppercase tracking-tighter leading-none">Legal Protocols</h2>
          <p className="text-[9px] font-black text-slate-500 uppercase tracking-widest mt-1">Operational Risk Agreement</p>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto p-6 space-y-10 pb-24">
        <div className="bg-blue-600/5 border border-blue-500/20 rounded-[2rem] p-6 flex gap-4 items-start">
          <div className="w-12 h-12 bg-blue-500/10 rounded-2xl flex items-center justify-center text-blue-500 shrink-0">
            <Scale size={24} />
          </div>
          <div>
            <h3 className="text-xs font-black text-white uppercase tracking-widest mb-1">Standard Terms v3.4</h3>
            <p className="text-[10px] text-slate-400 font-medium leading-relaxed">
              This agreement governs your access to the LumaTrade FX institutional interface and autonomous neural execution layers.
            </p>
          </div>
        </div>

        <div className="space-y-8">
          {sections.map((section, idx) => (
            <div key={idx} className="space-y-3 group">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-slate-900 border border-slate-800 rounded-xl transition-all group-hover:border-blue-500/30">
                  {section.icon}
                </div>
                <h4 className="text-xs font-black text-white uppercase tracking-widest">{section.title}</h4>
              </div>
              <p className="text-[11px] text-slate-500 leading-relaxed font-medium pl-1">
                {section.content}
              </p>
            </div>
          ))}
        </div>

        <div className="bg-slate-900/40 border border-slate-800 rounded-[2rem] p-6 space-y-4">
           <div className="flex items-center gap-2">
             <Info size={14} className="text-slate-500" />
             <span className="text-[9px] font-black text-slate-500 uppercase tracking-widest">Amendment Clause</span>
           </div>
           <p className="text-[10px] text-slate-600 font-bold uppercase tracking-tight leading-relaxed">
             LumaTrade reserves the right to modify these operational protocols at any time without prior notice. Continued use of the terminal after such changes shall constitute your consent to such changes.
           </p>
        </div>

        <div className="text-center pb-8">
          <p className="text-[9px] font-black text-slate-700 uppercase tracking-[0.3em]">Institutional Clearance: L-T PRO 772</p>
        </div>
      </div>
    </div>
  );
};

export default TermsScreen;
